import type { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'About — Blart',
  description: 'Blart is an AI art gallery offering unique machine-generated artworks as free digital downloads and museum-quality framed prints.',
};

export default function AboutPage() {
  return (
    <div className="pt-32 pb-20 px-6 md:px-10">
      <div className="max-w-2xl mx-auto">
        {/* Breadcrumb */}
        <nav className="mb-16 animate-fade-in">
          <ol className="flex items-center gap-2 text-xs tracking-wider uppercase text-blart-dim">
            <li><Link href="/" className="hover:text-blart-black transition-colors">Home</Link></li>
            <li>/</li>
            <li className="text-blart-black">About</li>
          </ol>
        </nav>

        <h1 className="font-display text-display mb-12 animate-slide-up">
          Art, made by<br />machines.
        </h1>

        <div className="space-y-8 text-blart-dim leading-relaxed animate-slide-up" style={{ animationDelay: '0.1s', opacity: 0 }}>
          <p className="text-lg text-blart-black/80">
            Blart is an experiment in algorithmic creativity. Every piece in our gallery 
            was generated by artificial intelligence — no human hand touched a brush, 
            no pencil met paper. Yet each work carries its own character, mood, and beauty.
          </p>

          <p>
            We believe AI-generated art deserves to exist in the physical world. That&apos;s 
            why every artwork on Blart is available as a free 4K digital download, and 
            can also be ordered as a museum-quality framed print, produced by our print 
            partner Prodigi and shipped anywhere in the world.
          </p>

          <p>
            Our prints use archival-grade giclée printing on fine art paper, mounted and 
            framed in classic frames with a lifespan of 100–200 years. Each print is 
            produced on demand, individually quality-checked, and shipped directly to you.
          </p>
        </div>

        {/* Process */}
        <div className="mt-20 pt-16 border-t border-blart-stone/50 animate-slide-up" style={{ animationDelay: '0.15s', opacity: 0 }}>
          <h2 className="font-display text-heading mb-10">How it works</h2>
          
          <div className="grid grid-cols-1 md:grid-cols-3 gap-10">
            <div>
              <span className="font-mono text-xs text-blart-ash block mb-3">01</span>
              <h3 className="font-display text-lg mb-2">Generate</h3>
              <p className="text-sm text-blart-dim leading-relaxed">
                Our AI artist creates new works daily across ten distinct styles — from 
                abstract expressionism to celestial compositions.
              </p>
            </div>
            <div>
              <span className="font-mono text-xs text-blart-ash block mb-3">02</span>
              <h3 className="font-display text-lg mb-2">Curate</h3>
              <p className="text-sm text-blart-dim leading-relaxed">
                Each piece is reviewed for quality and character before being 
                published to the gallery. Not everything makes the cut.
              </p>
            </div>
            <div>
              <span className="font-mono text-xs text-blart-ash block mb-3">03</span>
              <h3 className="font-display text-lg mb-2">Print</h3>
              <p className="text-sm text-blart-dim leading-relaxed">
                Choose your size and frame. Your print is produced on demand using 
                giclée archival printing and shipped worldwide.
              </p>
            </div>
          </div>
        </div>

        {/* Print Quality */}
        <div className="mt-20 pt-16 border-t border-blart-stone/50 animate-slide-up" style={{ animationDelay: '0.2s', opacity: 0 }}>
          <h2 className="font-display text-heading mb-10">Print quality</h2>
          
          <div className="space-y-6 text-sm text-blart-dim leading-relaxed">
            <div className="flex gap-6">
              <span className="text-blart-ash shrink-0 w-28 uppercase tracking-wider text-xs pt-0.5">Paper</span>
              <p>Enhanced Matte Art paper — 200gsm, acid-free, archival quality</p>
            </div>
            <div className="flex gap-6 border-t border-blart-stone/30 pt-6">
              <span className="text-blart-ash shrink-0 w-28 uppercase tracking-wider text-xs pt-0.5">Printing</span>
              <p>Giclée inkjet printing with pigment-based inks. 100–200 year lifespan under gallery conditions.</p>
            </div>
            <div className="flex gap-6 border-t border-blart-stone/30 pt-6">
              <span className="text-blart-ash shrink-0 w-28 uppercase tracking-wider text-xs pt-0.5">Frames</span>
              <p>Classic wooden frames with bevelled mount. Eight colour options: black, white, natural, antique silver, brown, antique gold, dark grey, light grey.</p>
            </div>
            <div className="flex gap-6 border-t border-blart-stone/30 pt-6">
              <span className="text-blart-ash shrink-0 w-28 uppercase tracking-wider text-xs pt-0.5">Sizes</span>
              <p>Five sizes from 8×10″ to 24×36″. All prints include a white bevelled mount.</p>
            </div>
            <div className="flex gap-6 border-t border-blart-stone/30 pt-6">
              <span className="text-blart-ash shrink-0 w-28 uppercase tracking-wider text-xs pt-0.5">Shipping</span>
              <p>Flat rate worldwide shipping. Printed and dispatched from the nearest Prodigi facility (UK, EU, US, or AU).</p>
            </div>
          </div>
        </div>

        {/* Downloads */}
        <div className="mt-20 pt-16 border-t border-blart-stone/50 animate-slide-up" style={{ animationDelay: '0.25s', opacity: 0 }}>
          <h2 className="font-display text-heading mb-6">Free downloads</h2>
          <p className="text-blart-dim leading-relaxed mb-6">
            Every artwork on Blart is available as a free 4K resolution download. No sign-up, 
            no watermarks, no restrictions. Use them as wallpapers, in projects, or print 
            them yourself — we just ask that you don&apos;t claim authorship.
          </p>
        </div>

        {/* For Developers / Agents */}
        <div className="mt-20 pt-16 border-t border-blart-stone/50 animate-slide-up" style={{ animationDelay: '0.3s', opacity: 0 }}>
          <h2 className="font-display text-heading mb-6">For developers &amp; AI agents</h2>
          <p className="text-blart-dim leading-relaxed mb-6">
            Blart is built to be agent-friendly. Our public API and structured data make it 
            easy for AI assistants, recommendation engines, and automation tools to discover, 
            filter, and recommend artworks to their users.
          </p>
          <div className="bg-blart-cream rounded-lg p-6 space-y-3 font-mono text-xs text-blart-dim">
            <p><span className="text-blart-ash">API</span> → <span className="text-blart-black">/api/gallery</span> — Browse and filter artworks</p>
            <p><span className="text-blart-ash">Docs</span> → <span className="text-blart-black">/llms.txt</span> — Machine-readable site guide</p>
            <p><span className="text-blart-ash">Data</span> → <span className="text-blart-black">JSON-LD / Schema.org</span> — Structured metadata on every page</p>
          </div>
        </div>

        {/* CTA */}
        <div className="mt-20 pt-16 border-t border-blart-stone/50 text-center animate-slide-up" style={{ animationDelay: '0.35s', opacity: 0 }}>
          <Link
            href="/gallery"
            className="inline-block bg-blart-black text-blart-white px-8 py-4 text-sm tracking-wider uppercase hover:bg-blart-dim transition-colors"
          >
            Explore the Gallery
          </Link>
        </div>
      </div>
    </div>
  );
}
