import Link from 'next/link';

export function Footer() {
  return (
    <footer className="border-t border-blart-stone/50 mt-24">
      <div className="max-w-[1800px] mx-auto px-6 md:px-10 py-12 md:py-16">
        <div className="grid grid-cols-1 md:grid-cols-4 gap-10">
          {/* Brand */}
          <div className="md:col-span-2">
            <Link href="/" className="font-display text-3xl font-light tracking-tight">
              blart<span className="text-blart-ash">.ai</span>
            </Link>
            <p className="mt-4 text-sm text-blart-dim max-w-sm leading-relaxed">
              Unique AI-generated art. Free 4K downloads. Museum-quality Giclée framed prints
              delivered worldwide.
            </p>
          </div>

          {/* Links */}
          <div>
            <h4 className="text-xs tracking-widest uppercase text-blart-ash mb-4">Browse</h4>
            <div className="flex flex-col gap-2">
              <Link href="/gallery" className="text-sm text-blart-dim hover:text-blart-black transition-colors">All Art</Link>
              <Link href="/gallery?filter=featured" className="text-sm text-blart-dim hover:text-blart-black transition-colors">Featured</Link>
              <Link href="/gallery?style=abstract" className="text-sm text-blart-dim hover:text-blart-black transition-colors">Abstract</Link>
              <Link href="/gallery?style=landscapes" className="text-sm text-blart-dim hover:text-blart-black transition-colors">Landscapes</Link>
              <Link href="/gallery?style=monochrome" className="text-sm text-blart-dim hover:text-blart-black transition-colors">Monochrome</Link>
            </div>
          </div>

          <div>
            <h4 className="text-xs tracking-widest uppercase text-blart-ash mb-4">Info</h4>
            <div className="flex flex-col gap-2">
              <Link href="/about" className="text-sm text-blart-dim hover:text-blart-black transition-colors">About</Link>
              <Link href="/api/gallery" className="text-sm text-blart-dim hover:text-blart-black transition-colors">API</Link>
              <Link href="/llms.txt" className="text-sm text-blart-dim hover:text-blart-black transition-colors">llms.txt</Link>
            </div>
          </div>
        </div>

        <div className="mt-12 pt-8 border-t border-blart-stone/30 flex flex-col md:flex-row justify-between items-center gap-4">
          <p className="text-xs text-blart-ash">
            © {new Date().getFullYear()} Blart.ai — All art generated by AI. Prints by Prodigi.
          </p>
          <p className="text-xs text-blart-ash">
            Built with care in Far North Queensland
          </p>
        </div>
      </div>
    </footer>
  );
}
